import 'package:illemo/src/features/emotions/domain/models/category.dart';

enum Emotion {
  joy('joy', 'Joy', Category.joyful),
  joyGrateful('joy.grateful', 'Grateful', Category.joyful, parentId: 'joy'),
  joyGratefulAppreciative('joy.grateful.appreciative', 'Appreciative', Category.joyful,
      parentId: 'joy.grateful'),
  joyGratefulTouched('joy.grateful.touched', 'Touched', Category.joyful, parentId: 'joy.grateful'),
  joyGratefulBlessed('joy.grateful.blessed', 'Blessed', Category.joyful, parentId: 'joy.grateful'),
  joyHopeful('joy.hopeful', 'Hopeful', Category.joyful, parentId: 'joy'),
  joyHopefulOptimistic('joy.hopeful.optimistic', 'Optimistic', Category.joyful,
      parentId: 'joy.hopeful'),
  joyHopefulEncouraged('joy.hopeful.encouraged', 'Encouraged', Category.joyful,
      parentId: 'joy.hopeful'),
  joyHopefulInspired('joy.hopeful.inspired', 'Inspired', Category.joyful, parentId: 'joy.hopeful'),
  joyPlayful('joy.playful', 'Playful', Category.joyful, parentId: 'joy'),
  joyPlayfulEnergetic('joy.playful.energetic', 'Energetic', Category.joyful,
      parentId: 'joy.playful'),
  joyPlayfulSilly('joy.playful.silly', 'Silly', Category.joyful, parentId: 'joy.playful'),
  joyPlayfulLighthearted('joy.playful.lighthearted', 'Lighthearted', Category.joyful,
      parentId: 'joy.playful'),
  joyProud('joy.proud', 'Proud', Category.joyful, parentId: 'joy'),
  joyProudConfident('joy.proud.confident', 'Confident', Category.joyful, parentId: 'joy.proud'),
  joyProudAccomplished('joy.proud.accomplished', 'Accomplished', Category.joyful,
      parentId: 'joy.proud'),
  joyProudWorthy('joy.proud.worthy', 'Worthy', Category.joyful, parentId: 'joy.proud'),
  joyContent('joy.content', 'Content', Category.joyful, parentId: 'joy'),
  joyContentPeaceful('joy.content.peaceful', 'Peaceful', Category.joyful, parentId: 'joy.content'),
  joyContentSatisfied('joy.content.satisfied', 'Satisfied', Category.joyful,
      parentId: 'joy.content'),
  joyContentFulfilled('joy.content.fulfilled', 'Fulfilled', Category.joyful,
      parentId: 'joy.content'),
  joyExcited('joy.excited', 'Excited', Category.joyful, parentId: 'joy'),
  joyExcitedEager('joy.excited.eager', 'Eager', Category.joyful, parentId: 'joy.excited'),
  joyExcitedEnthusiastic('joy.excited.enthusiastic', 'Enthusiastic', Category.joyful,
      parentId: 'joy.excited'),
  joyExcitedThrilled('joy.excited.thrilled', 'Thrilled', Category.joyful, parentId: 'joy.excited'),
  sadness('sadness', 'Sadness', Category.sad),
  sadnessLonely('sadness.lonely', 'Lonely', Category.sad, parentId: 'sadness'),
  sadnessLonelyIsolated('sadness.lonely.isolated', 'Isolated', Category.sad,
      parentId: 'sadness.lonely'),
  sadnessLonelyDisconnected('sadness.lonely.disconnected', 'Disconnected', Category.sad,
      parentId: 'sadness.lonely'),
  sadnessLonelyLeftOut('sadness.lonely.left_out', 'Left out', Category.sad,
      parentId: 'sadness.lonely'),
  sadnessHurt('sadness.hurt', 'Hurt', Category.sad, parentId: 'sadness'),
  sadnessHurtWounded('sadness.hurt.wounded', 'Wounded', Category.sad, parentId: 'sadness.hurt'),
  sadnessHurtLetDown('sadness.hurt.let_down', 'Let down', Category.sad, parentId: 'sadness.hurt'),
  sadnessHurtBetrayed('sadness.hurt.betrayed', 'Betrayed', Category.sad, parentId: 'sadness.hurt'),
  sadnessVulnerable('sadness.vulnerable', 'Vulnerable', Category.sad, parentId: 'sadness'),
  sadnessVulnerableExposed('sadness.vulnerable.exposed', 'Exposed', Category.sad,
      parentId: 'sadness.vulnerable'),
  sadnessVulnerableFragile('sadness.vulnerable.fragile', 'Fragile', Category.sad,
      parentId: 'sadness.vulnerable'),
  sadnessVulnerableTender('sadness.vulnerable.tender', 'Tender', Category.sad,
      parentId: 'sadness.vulnerable'),
  sadnessExhausted('sadness.exhausted', 'Exhausted', Category.sad, parentId: 'sadness'),
  sadnessExhaustedDrained('sadness.exhausted.drained', 'Drained', Category.sad,
      parentId: 'sadness.exhausted'),
  sadnessExhaustedDepleted('sadness.exhausted.depleted', 'Depleted', Category.sad,
      parentId: 'sadness.exhausted'),
  sadnessExhaustedSpent('sadness.exhausted.spent', 'Spent', Category.sad,
      parentId: 'sadness.exhausted'),
  sadnessGrief('sadness.grief', 'Grief', Category.sad, parentId: 'sadness'),
  sadnessGriefLoss('sadness.grief.loss', 'Loss', Category.sad, parentId: 'sadness.grief'),
  sadnessGriefMourning('sadness.grief.mourning', 'Mourning', Category.sad,
      parentId: 'sadness.grief'),
  sadnessGriefHeartbroken('sadness.grief.heartbroken', 'Heartbroken', Category.sad,
      parentId: 'sadness.grief'),
  sadnessHopeless('sadness.hopeless', 'Hopeless', Category.sad, parentId: 'sadness'),
  sadnessHopelessPowerless('sadness.hopeless.powerless', 'Powerless', Category.sad,
      parentId: 'sadness.hopeless'),
  sadnessHopelessDespairing('sadness.hopeless.despairing', 'Despairing', Category.sad,
      parentId: 'sadness.hopeless'),
  sadnessHopelessEmpty('sadness.hopeless.empty', 'Empty', Category.sad,
      parentId: 'sadness.hopeless'),
  anger('anger', 'Anger', Category.mad),
  angerFrustrated('anger.frustrated', 'Frustrated', Category.mad, parentId: 'anger'),
  angerFrustratedAnnoyed('anger.frustrated.annoyed', 'Annoyed', Category.mad,
      parentId: 'anger.frustrated'),
  angerFrustratedBlocked('anger.frustrated.blocked', 'Blocked', Category.mad,
      parentId: 'anger.frustrated'),
  angerFrustratedImpatient('anger.frustrated.impatient', 'Impatient', Category.mad,
      parentId: 'anger.frustrated'),
  angerResentful('anger.resentful', 'Resentful', Category.mad, parentId: 'anger'),
  angerResentfulBitter('anger.resentful.bitter', 'Bitter', Category.mad,
      parentId: 'anger.resentful'),
  angerResentfulIndignant('anger.resentful.indignant', 'Indignant', Category.mad,
      parentId: 'anger.resentful'),
  angerResentfulOffended('anger.resentful.offended', 'Offended', Category.mad,
      parentId: 'anger.resentful'),
  angerJealous('anger.jealous', 'Jealous', Category.mad, parentId: 'anger'),
  angerJealousEnvious('anger.jealous.envious', 'Envious', Category.mad, parentId: 'anger.jealous'),
  angerJealousSuspicious('anger.jealous.suspicious', 'Suspicious', Category.mad,
      parentId: 'anger.jealous'),
  angerJealousUnsettled('anger.jealous.unsettled', 'Unsettled', Category.mad,
      parentId: 'anger.jealous'),
  angerCritical('anger.critical', 'Critical', Category.mad, parentId: 'anger'),
  angerCriticalSceptical('anger.critical.sceptical', 'Sceptical', Category.mad,
      parentId: 'anger.critical'),
  angerCriticalDismissive('anger.critical.dismissive', 'Dismissive', Category.mad,
      parentId: 'anger.critical'),
  angerCriticalExasperated('anger.critical.exasperated', 'Exasperated', Category.mad,
      parentId: 'anger.critical'),
  angerOverwhelmed('anger.overwhelmed', 'Overwhelmed', Category.mad, parentId: 'anger'),
  angerOverwhelmedStressed('anger.overwhelmed.stressed', 'Stressed', Category.mad,
      parentId: 'anger.overwhelmed'),
  angerOverwhelmedFrantic('anger.overwhelmed.frantic', 'Frantic', Category.mad,
      parentId: 'anger.overwhelmed'),
  angerOverwhelmedOutOfControl('anger.overwhelmed.out_of_control', 'Out of control', Category.mad,
      parentId: 'anger.overwhelmed'),
  angerWithdrawn('anger.withdrawn', 'Withdrawn', Category.mad, parentId: 'anger'),
  angerWithdrawnNumb('anger.withdrawn.numb', 'Numb', Category.mad, parentId: 'anger.withdrawn'),
  angerWithdrawnDetached('anger.withdrawn.detached', 'Detached', Category.mad,
      parentId: 'anger.withdrawn'),
  angerWithdrawnCheckedOut('anger.withdrawn.checked_out', 'Checked out', Category.mad,
      parentId: 'anger.withdrawn'),
  fear('fear', 'Fear', Category.scared),
  fearAnxious('fear.anxious', 'Anxious', Category.scared, parentId: 'fear'),
  fearAnxiousWorried('fear.anxious.worried', 'Worried', Category.scared, parentId: 'fear.anxious'),
  fearAnxiousApprehensive('fear.anxious.apprehensive', 'Apprehensive', Category.scared,
      parentId: 'fear.anxious'),
  fearAnxiousUneasy('fear.anxious.uneasy', 'Uneasy', Category.scared, parentId: 'fear.anxious'),
  fearInsecure('fear.insecure', 'Insecure', Category.scared, parentId: 'fear'),
  fearInsecureInferior('fear.insecure.inferior', 'Inferior', Category.scared,
      parentId: 'fear.insecure'),
  fearInsecureUncertain('fear.insecure.uncertain', 'Uncertain', Category.scared,
      parentId: 'fear.insecure'),
  fearInsecureUnworthy('fear.insecure.unworthy', 'Unworthy', Category.scared,
      parentId: 'fear.insecure'),
  fearScared('fear.scared', 'Scared', Category.scared, parentId: 'fear'),
  fearScaredThreatened('fear.scared.threatened', 'Threatened', Category.scared,
      parentId: 'fear.scared'),
  fearScaredPanicked('fear.scared.panicked', 'Panicked', Category.scared, parentId: 'fear.scared'),
  fearScaredDreading('fear.scared.dreading', 'Dreading', Category.scared, parentId: 'fear.scared'),
  fearRejected('fear.rejected', 'Rejected', Category.scared, parentId: 'fear'),
  fearRejectedExcluded('fear.rejected.excluded', 'Excluded', Category.scared,
      parentId: 'fear.rejected'),
  fearRejectedUnwanted('fear.rejected.unwanted', 'Unwanted', Category.scared,
      parentId: 'fear.rejected'),
  fearRejectedAbandoned('fear.rejected.abandoned', 'Abandoned', Category.scared,
      parentId: 'fear.rejected'),
  fearHelpless('fear.helpless', 'Helpless', Category.scared, parentId: 'fear'),
  fearHelplessTrapped('fear.helpless.trapped', 'Trapped', Category.scared,
      parentId: 'fear.helpless'),
  fearHelplessStuck('fear.helpless.stuck', 'Stuck', Category.scared, parentId: 'fear.helpless'),
  fearHelplessPowerless('fear.helpless.powerless', 'Powerless', Category.scared,
      parentId: 'fear.helpless'),
  fearConfused('fear.confused', 'Confused', Category.scared, parentId: 'fear'),
  fearConfusedLost('fear.confused.lost', 'Lost', Category.scared, parentId: 'fear.confused'),
  fearConfusedTorn('fear.confused.torn', 'Torn', Category.scared, parentId: 'fear.confused'),
  fearConfusedConflicted('fear.confused.conflicted', 'Conflicted', Category.scared,
      parentId: 'fear.confused'),
  disgust('disgust', 'Disgust', Category.peaceful),
  disgustDisapproving('disgust.disapproving', 'Disapproving', Category.peaceful,
      parentId: 'disgust'),
  disgustDisapprovingJudging('disgust.disapproving.judging', 'Judging', Category.peaceful,
      parentId: 'disgust.disapproving'),
  disgustDisapprovingAppalled('disgust.disapproving.appalled', 'Appalled', Category.peaceful,
      parentId: 'disgust.disapproving'),
  disgustDisapprovingShocked('disgust.disapproving.shocked', 'Shocked', Category.peaceful,
      parentId: 'disgust.disapproving'),
  disgustDisappointed('disgust.disappointed', 'Disappointed', Category.peaceful,
      parentId: 'disgust'),
  disgustDisappointedLetDown('disgust.disappointed.let_down', 'Let down', Category.peaceful,
      parentId: 'disgust.disappointed'),
  disgustDisappointedDisillusioned(
      'disgust.disappointed.disillusioned', 'Disillusioned', Category.peaceful,
      parentId: 'disgust.disappointed'),
  disgustDisappointedDeflated('disgust.disappointed.deflated', 'Deflated', Category.peaceful,
      parentId: 'disgust.disappointed'),
  disgustAvoidant('disgust.avoidant', 'Avoidant', Category.peaceful, parentId: 'disgust'),
  disgustAvoidantHesitant('disgust.avoidant.hesitant', 'Hesitant', Category.peaceful,
      parentId: 'disgust.avoidant'),
  disgustAvoidantReluctant('disgust.avoidant.reluctant', 'Reluctant', Category.peaceful,
      parentId: 'disgust.avoidant'),
  disgustAvoidantResistant('disgust.avoidant.resistant', 'Resistant', Category.peaceful,
      parentId: 'disgust.avoidant'),
  disgustRepulsed('disgust.repulsed', 'Repulsed', Category.peaceful, parentId: 'disgust'),
  disgustRepulsedUnsettled('disgust.repulsed.unsettled', 'Unsettled', Category.peaceful,
      parentId: 'disgust.repulsed'),
  disgustRepulsedRevolted('disgust.repulsed.revolted', 'Revolted', Category.peaceful,
      parentId: 'disgust.repulsed'),
  disgustRepulsedBothered('disgust.repulsed.bothered', 'Bothered', Category.peaceful,
      parentId: 'disgust.repulsed'),
  disgustAwful('disgust.awful', 'Awful', Category.peaceful, parentId: 'disgust'),
  disgustAwfulTerrible('disgust.awful.terrible', 'Terrible', Category.peaceful,
      parentId: 'disgust.awful'),
  disgustAwfulDreadful('disgust.awful.dreadful', 'Dreadful', Category.peaceful,
      parentId: 'disgust.awful'),
  disgustAwfulHorrible('disgust.awful.horrible', 'Horrible', Category.peaceful,
      parentId: 'disgust.awful'),
  surprise('surprise', 'Surprise', Category.powerful),
  surpriseStartled('surprise.startled', 'Startled', Category.powerful, parentId: 'surprise'),
  surpriseStartledShocked('surprise.startled.shocked', 'Shocked', Category.powerful,
      parentId: 'surprise.startled'),
  surpriseStartledShaken('surprise.startled.shaken', 'Shaken', Category.powerful,
      parentId: 'surprise.startled'),
  surpriseStartledOffGuard('surprise.startled.off_guard', 'Off guard', Category.powerful,
      parentId: 'surprise.startled'),
  surpriseAmazed('surprise.amazed', 'Amazed', Category.powerful, parentId: 'surprise'),
  surpriseAmazedAstonished('surprise.amazed.astonished', 'Astonished', Category.powerful,
      parentId: 'surprise.amazed'),
  surpriseAmazedAwestruck('surprise.amazed.awestruck', 'Awestruck', Category.powerful,
      parentId: 'surprise.amazed'),
  surpriseAmazedStunned('surprise.amazed.stunned', 'Stunned', Category.powerful,
      parentId: 'surprise.amazed'),
  surpriseConfused('surprise.confused', 'Confused', Category.powerful, parentId: 'surprise'),
  surpriseConfusedPuzzled('surprise.confused.puzzled', 'Puzzled', Category.powerful,
      parentId: 'surprise.confused'),
  surpriseConfusedPerplexed('surprise.confused.perplexed', 'Perplexed', Category.powerful,
      parentId: 'surprise.confused'),
  surpriseConfusedDisoriented('surprise.confused.disoriented', 'Disoriented', Category.powerful,
      parentId: 'surprise.confused'),
  surpriseCurious('surprise.curious', 'Curious', Category.powerful, parentId: 'surprise'),
  surpriseCuriousInterested('surprise.curious.interested', 'Interested', Category.powerful,
      parentId: 'surprise.curious'),
  surpriseCuriousIntrigued('surprise.curious.intrigued', 'Intrigued', Category.powerful,
      parentId: 'surprise.curious'),
  surpriseCuriousFascinated('surprise.curious.fascinated', 'Fascinated', Category.powerful,
      parentId: 'surprise.curious'),
  surpriseMoved('surprise.moved', 'Moved', Category.powerful, parentId: 'surprise'),
  surpriseMovedTouched('surprise.moved.touched', 'Touched', Category.powerful,
      parentId: 'surprise.moved'),
  surpriseMovedSpeechless('surprise.moved.speechless', 'Speechless', Category.powerful,
      parentId: 'surprise.moved'),
  surpriseMovedOverwhelmed('surprise.moved.overwhelmed', 'Overwhelmed', Category.powerful,
      parentId: 'surprise.moved');

  const Emotion(this.id, this.label, this.category, {this.parentId});

  final String id;
  final String label;
  final Category category;
  final String? parentId;

  bool get isCategory => parentId == null;

  static final Map<String, Emotion> _byId = {for (final emotion in values) emotion.id: emotion};

  static List<Emotion> get categories => values.where((emotion) => emotion.isCategory).toList();

  static Emotion categoryRoot(Category category) =>
      categories.firstWhere((emotion) => emotion.category == category);

  static List<Emotion> specificsFor(Category category) => childrenOf(categoryRoot(category).id);

  static Emotion get(String id) =>
      _byId[id] ?? (throw ArgumentError.value(id, 'id', 'Unknown emotion'));

  static List<Emotion> childrenOf(String id) =>
      values.where((emotion) => emotion.parentId == id).toList();

  @override
  String toString() => label;
}
