name: illemo
description: A emotion tracking wellness app.

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  force_update_helper: ^0.1.5
  go_router: ^14.6.2
  intl: ^0.19.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  # a tool for running code generators
  build_runner: ^2.4.13
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  random_string: ^2.3.1
  # the code generator
  riverpod_generator: ^2.6.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/common/
    - path: assets/dev/
      flavors:
        - dev
    - path: assets/prod/
      flavors:
        - production
